const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART'
}

export default CartActionTypes


//CLEAR_ITEM (FROM CHECKOUT PAGE WITH X ICON)
//REMOVE_ITEM (WHEN THE QUANTITY DECREASE TILL 1 THEN ON CLICK GET REMOVED )